# Python dictionary (translatable to JSON) that has purchase categories as keys and a list of discounts as the values for those keys. Each element in the list 
# is a dictionary of its own, with a key of 'deal' with details about the promotion and 'merchant' with relevant location information.
API_KEY = '2h2VgQ_0QQGxDS4M3Gv-ZSv0FVCs1hOTqjNU8DNOy57DBVVsLqCRL6ScBeX_FRF7f1UZHQNdo9AIdZHcZusxaVQHUqmf7TP-PclMxQg_MrJaQqOf3EHW5lad060HW3Yx'

discounts_by_category = {
    'activities-events': [],
    'adult': [],
    'audio': [],
    'automotive': [{
        'deal': {
            'id': 437251,
            'title': '$100 Toward Windshield Replacement or Insurance Deductible Plus Gift Card from Cascade Auto Glass (86% Off)  ',
            'short_title': '86% Off Windshield Replacement from Cascade Auto Glass',
            'description': '$100 Towards Full Windshield Replacement or Insurance Deductible and $25 Restaurant Gift Card Cascade Auto Glass techs travel to replace windshields with mobile service to homes and offices, outfitting rides with Original Equipment Manufactured (OEM) quality windshields in approximately one hour. Cascade deals directly with insurance companies when customers choose to apply their $100 voucher toward a deductible or competitively-priced windshield. Services are backed by a nationwide warranty. $25 gift card for restaurant.com has no expiration date and will be mailed within 10-12 days of the windshield being replaced by Cascade Auto Glass, along with instructions on how to choose a restaurant and redeem. The gift card is valid throughout the U.S., however some restrictions apply.',
            'fine_print': 'Limit 1 per person, may buy 1 additional as gift. Must use promotional value in 1 visit. Valid only for option purchased. Limit 1 per vehicle. Appointment required; subject to availability. Valid only within specific zip codes.. $25 restaurant gift card is for restaurant.com. Some restrictions apply. Gift card does not expire. Valid throughout the US. Gift card will be mailed to customer within 10–12 days of windshield being replaced. Offer is not eligible for voucher promo codes or other discounts.',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/437251/click?api_key=FvDeXygs',
            'price': 14.0,
            'value': 100.0,
            'discount_amount': 86.0,
            'discount_percentage': 0.86,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Automotive',
            'category_slug': 'automotive',
            'image_url': 'https://api.discountapi.com/v2/deals/437251/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2019-03-23T00:00:00Z',
            'created_at': '2018-03-28T10:44:54Z',
            'updated_at': '2018-04-16T10:44:46Z',
            'merchant': {
                'id': 42975,
                'name': 'Cascade Auto Glass',
                'address': 'E Jefferson Blvd. and S Michigan St.',
                'locality': 'South Bend',
                'region': 'IN',
                'postal_code': '46601',
                'country': 'US',
                'latitude': 41.6750321,
                'longitude': -86.2503239,
                'url': 'http://www.cascadeautoglass.com/'
            }
        }
    }, {
        'deal': {
            'id': 256683,
            'title': "$43 for an Auto-Maintenance Package at Bucky's ($154 Value). 16 Locations Available. ",
            'short_title': '72% Off Auto-Maintenance Package',
            'description': 'The Deal $43 for an auto-maintenance package ($154 value) Choose from 16 locations. The maintenance package includes a premium oil and filter change with tire rotation as well as a full vehicle inspection. Staff members top of all fluids and check the brakes, suspension, battery, and cooling system for proper function.',
            'fine_print': 'Limit 1 per person, may buy 1 additional as a gift. Valid only for location purchased. Appointment required. Subject to availability. Valid for up to 6 quarts of oil. Extra fee applies for diesel, synthetic oil, or canister filters. Not valid for commercial vehicles, large trucks, or motor homes. All services per voucher must be redeemed during a single visit and used by the same vehicle. May be repurchased every 30 days.',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/256683/click?api_key=FvDeXygs',
            'price': 44.5,
            'value': 153.9,
            'discount_amount': 109.4,
            'discount_percentage': 0.7108512020792722,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Automotive',
            'category_slug': 'automotive',
            'image_url': 'https://api.discountapi.com/v2/deals/256683/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-06-16T00:00:00Z',
            'created_at': '2018-02-16T17:23:50Z',
            'updated_at': '2018-04-15T14:01:39Z',
            'merchant': {
                'id': 155363,
                'name': "Bucky's Complete Auto Repair",
                'address': '10002 Lakeview Ave SW',
                'locality': 'Lakewood',
                'region': 'WA',
                'postal_code': '98499',
                'country': 'US',
                'latitude': 47.1662093,
                'longitude': -122.4948551,
                'phone_number': '+12535888600',
                'url': 'http://www.buckys.com/'
            }
        }
    }],
    'automotive-services': [{
        'deal': {
            'id': 357741,
            'title': 'Standard Brake Service with Lifetime Warranty, or State Inspection at Meineke Car Care Center (Up to 45% Off)',
            'short_title': 'Up to 45% Off Automotive Services at Meineke Car Care Center',
            'description': 'Choice of: Standard Brake Service on One Axle Standard Brake Service on One Axle with Lifetime Warranty Virginia State Inspection Choose from six available locations: 1837 Laskin Road, Virginia Beach 4609 G. Washington Memorial Highway, Yorktown 415 Oriana Rd., Newport News 79 W Mercury Boulevard, Hampton 6399 Indian River Rd., Virginia Beach 399 2nd Street, Williamsburg Not valid for luxury brands, trucks, vans, or over-sized SUV’s. State Inspection is only valid in the state of Virginia.',
            'fine_print': "May be repurchased every 180 days. Limit 1 per person, may buy 1 additional as gift. Limit 1 per visit. Must use promotional value in 1 visit. Valid only for option purchased. Brake pad offer is valid for light passenger vehicles, cars, and standard SUV's. Not valid for luxury brands, trucks, vans, or over-sized SUV's. Brake rotors, caliper service, and brake fluid service available for an additional charge. State Inspection is only valid in the state of Virginia. Valid only for location purchased.",
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/357741/click?api_key=FvDeXygs',
            'price': 10.0,
            'value': 16.0,
            'discount_amount': 6.0,
            'discount_percentage': 0.375,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Automotive Services',
            'category_slug': 'automotive-services',
            'image_url': 'https://api.discountapi.com/v2/deals/357741/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-06-09T00:00:00Z',
            'created_at': '2018-03-11T13:50:50Z',
            'updated_at': '2018-04-13T11:38:53Z',
            'merchant': {
                'id': 67717,
                'name': 'Meineke Car Care Center',
                'address': '6399 Indian River Road',
                'locality': 'Virginia Beach',
                'region': 'VA',
                'postal_code': '23464',
                'country': 'US',
                'latitude': 36.8167929,
                'longitude': -76.213051,
                'phone_number': '+17574201780',
                'url': 'https://www.meineke.com/'
            }
        }
    }, {
        'deal': {
            'id': 115114,
            'title': 'One or Two vouchers, Each Good for One VIP Car Wash with Armor All Extreme Shine Wax (Up to 51% Off)  ',
            'short_title': 'Up to 51% Off VIP Car Wash with Armor All Extreme Shine Wax',
            'description': 'Choose Between Two Options $29.99 for one VIP car wash and Armor All extreme shine wax ($60 value) $59 for two vouchers, each good for one VIP car wash and Armor All extreme shine wax ($120 value)',
            'fine_print': 'Valid only Monday - Friday 8a-5p. Extra $2 fee for SUV’s & extra $4 fee for oversized vehicles to be collected at time of service. Tax also to be collected at time of service. Limit 1 per person. Valid only for option purchased. May be repurchased every 90 days.',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/115114/click?api_key=FvDeXygs',
            'price': 29.5,
            'value': 60.0,
            'discount_amount': 30.5,
            'discount_percentage': 0.5083333333333333,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Automotive Services',
            'category_slug': 'automotive-services',
            'image_url': 'https://api.discountapi.com/v2/deals/115114/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-06-16T00:00:00Z',
            'created_at': '2018-02-16T15:35:17Z',
            'updated_at': '2018-04-15T12:40:45Z',
            'merchant': {
                'id': 72713,
                'name': 'Bethpage Car Wash',
                'address': '4110 Hempstead Turnpike',
                'locality': 'Bethpage',
                'region': 'NY',
                'postal_code': '11714',
                'country': 'US',
                'latitude': 40.7250155,
                'longitude': -73.4840089,
                'phone_number': '+15164650303',
                'url': 'http://bethpagecarwash.com/'
            }
        }
    }],
    'baby': [],
    'bars-clubs': [],
    'beauty_health': [],
    'boot-camp': [],
    'bowling': [],
    'bridal': [],
    'chiropractic': [],
    'city-tours': [{
        'deal': {
            'id': 289465,
            'title': 'Clue-Gathering Walking Adventure Game for Two, Four or Six from 3Quest Challenge (Up to 52% Off) ',
            'short_title': 'Up to 52% Off Admission at 3Quest Challenge',
            'description': 'Choice of: 3Quest Challenge for Two 3Quest Challenge for Four 3Quest Challenge for Six How it Works When you buy your tickets, you’ll make a reservation for your start time and date You’ll get an email with the Home Base location, which is where you’ll start your quest At the designated start time, you’ll go to Home Base and open the 3Quest email From there, you’ll be prompted through the game via your smartphone',
            'fine_print': "Online registration required. May be repurchased every 90 days. Merchant's standard cancellation policy applies (any fees not to exceed voucher price). Limit 1 per person, may buy 1 additional as gift. Limit 1 per visit. Valid only for option purchased. All goods or services must be used by the same person.",
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/289465/click?api_key=FvDeXygs',
            'price': 19.0,
            'value': 39.95,
            'discount_amount': 20.950000000000003,
            'discount_percentage': 0.5244055068836045,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'City Tours',
            'category_slug': 'city-tours',
            'image_url': 'https://api.discountapi.com/v2/deals/289465/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-06-23T00:00:00Z',
            'created_at': '2018-02-23T18:29:42Z',
            'updated_at': '2018-04-15T11:04:39Z',
            'merchant': {
                'id': 163999,
                'name': '3Quest Challenge',
                'address': '836 Reynolds St',
                'locality': 'Augusta',
                'region': 'GA',
                'postal_code': '30901',
                'country': 'US',
                'latitude': 33.476352,
                'longitude': -81.965974,
                'phone_number': '+18006976176'
            }
        }
    }],
    'clothing': [{
        'deal': {
            'id': 133036,
            'title': "Vincent Cavallo Men's Wingtip Monk-Strap Dress Shoes",
            'short_title': "Vincent Cavallo Men's Wingtip Monk-Strap Dress Shoes",
            'description': 'Vincent Cavallo Men’s Wingtip Monk-Strap Dress Shoes Wingtip dress shoes for formal wear Hard-burnished, brogue detail Single or double monk-strap design Buckle closure Padded insole for added comfort Slip-resistant outsole Medium width Materials; Upper: faux leather Outsole: rubber Fit true to size For post-purchase inquiries, please contact customer support. Sold by Groupon Goods. View the products FAQ to learn more.',
            'fine_print': 'Free returns Most orders are delivered within 7 business days from the purchase date. Shipping questions? Does not ship to PO boxes/AK/HI/Canada/Puerto Rico How is the strike-through price determined?',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/133036/click?api_key=FvDeXygs',
            'price': 29.99,
            'value': 89.99,
            'discount_amount': 60.0,
            'discount_percentage': 0.666740748972108,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Clothing',
            'category_slug': 'clothing',
            'image_url': 'https://api.discountapi.com/v2/deals/133036/image?api_key=FvDeXygs',
            'online': True,
            'expires_at': '2999-01-01T00:00:00Z',
            'created_at': '2018-02-16T15:44:48Z',
            'updated_at': '2018-03-12T08:45:14Z',
            'merchant': {
                'id': 85758,
                'name': "Vincent Cavallo Men's Wingtip Monk-Strap Dress Shoes"
            }
        }
    }, {
        'deal': {
            'id': 129383,
            'title': "Franco Vanucci Lorenzo Men's Driving Shoes",
            'short_title': "Franco Vanucci Lorenzo Men's Driving Shoes",
            'description': 'Franco Vanucci Lorenzo Men’s Driving Shoes Men’s driving shoes Come with cushioned insole for added comfort Made with decorative buckle Features flexible outsole for traction Round toe design Slip-on style Pair well with slacks or suits Width: medium Materials: Upper: faux-leather Lining and sock: synthetic Outsole: rubber Suggested care instructions Fit true to size About Franco Vanucci Franco Vanucci is the men’s branch of the Rasolli Footwear tree. Started in 1986, Rasolli’s first focus was fashionable women’s shoes, but its expertise in both high quality and reasonable prices pushed the brand to expand their work into the men’s side of the business. Franco Vanucci tends toward a modern, European-leaning aesthetic with casual slip-on loafers and fashion-forward dress shoes. For post-purchase inquiries, please contact customer support. Sold by Groupon Goods. View the products FAQ to learn more.',
            'fine_print': 'Free returns Most orders are delivered within 7 business days from the purchase date. Shipping questions? Does not ship to PO boxes/AK/HI/Puerto Rico How is the strike-through price determined?',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/129383/click?api_key=FvDeXygs',
            'price': 31.99,
            'value': 98.0,
            'discount_amount': 66.01,
            'discount_percentage': 0.6735714285714286,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Clothing',
            'category_slug': 'clothing',
            'image_url': 'https://api.discountapi.com/v2/deals/129383/image?api_key=FvDeXygs',
            'online': True,
            'expires_at': '2999-01-01T00:00:00Z',
            'created_at': '2018-02-16T15:43:18Z',
            'updated_at': '2018-03-12T08:45:17Z',
            'merchant': {
                'id': 82416,
                'name': "Franco Vanucci Lorenzo Men's Driving Shoes"
            }
        }
    }, {
        'deal': {
            'id': 28152,
            'title': "Berto Romani Men's Slim-Fit Button-Down Cotton-Blend Shirt",
            'short_title': "Berto Romani Men's Slim-Fit Button-Down Cotton-Blend Shirt",
            'description': 'Berto Romani Men’s Slim-Fit Button-Down Cotton-Blend Shirt Long-sleeve shirt for casual wear Slim-fit, button-down design Contrast inner collar, cuffs, and button placket Adjustable buttoned barrel cuffs Wrinkle-resistant fabric Materials: 60% cotton, 40% polyester Suggested care instructions Men’s sizing chart For post-purchase inquiries, please contact customer support. Sold by Groupon Goods. View the products FAQ to learn more.',
            'fine_print': 'Free returns Most orders are delivered within 7 business days from the purchase date. Shipping questions? Does not ship to PO boxes/AK/HI/Canada/Puerto Rico How is the strike-through price determined?',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/28152/click?api_key=FvDeXygs',
            'price': 14.99,
            'value': 90.99,
            'discount_amount': 76.0,
            'discount_percentage': 0.8352566216067701,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Clothing',
            'category_slug': 'clothing',
            'image_url': 'https://api.discountapi.com/v2/deals/28152/image?api_key=FvDeXygs',
            'online': True,
            'expires_at': '2999-01-01T00:00:00Z',
            'created_at': '2018-02-16T13:51:49Z',
            'updated_at': '2018-04-15T10:39:57Z',
            'merchant': {
                'id': 23725,
                'name': "Berto Romani Men's Slim-Fit Button-Down Cotton-Blend Shirt"
            }
        }
    }],
    'college': [],
    'comedy-clubs': [],
    'concerts': [],
    'crafts_hobbies': [],
    'dance-classes': [],
    'dental': [{
        'deal': {
            'id': 443331,
            'title': 'Individual and Family Discount Plan with Exam and X-Rays\xa0at Great Expressions Dental Centers',
            'short_title': 'Smile Protection Plan Membership at Great Expressions Dental Centers',
            'description': 'Choose from 26 dentists across 26 Texas locations Smile Protection Plan Includes: 18 months of savings and discounts up to 60% off Family Plan eligibility: spouse and dependent children under 18 (or up to age 26 if attending school on a full-time basis, up to 10 people) 1 Custom take-home Opalescence teeth whitening kit with valid options Example savings include: Comprehensive new patient oral exam ($110 Value) –> Free with plan Periodic oral exam ($56 Value) –> Free with plan Complete Full Mouth X-Rays ($165 Value) –> Free with plan Preventative Cleanings ($121 Value) –> You pay $61 Crown – Porcelain/Ceramic ($1,486 Value) –> You pay $1,030 Composite Filling – One Surface, Posterior ($242 Value) –> You pay $122 Great Expressions provides quality dental care. The Smile Protection plan is not insurance. This is a licensed discount medical plan. Members of the plan save 20 to 60% on a wide range of dental services with unlimited access to savings. The plan enables clients to get the services they need at a more affordable price. Click here for more information on the Smile Protection plan.',
            'fine_print': 'Consultation required; non-candidates and other refund requests will be honored before service provided. Appointment required. Limit 1 per person. Valid only for option purchased. Amount paid is the amount returned to the patient in lieu of redeeming the voucher if, upon presentation and consultation, the patient is not eligible to receive professional services advertised in the offering. The Smile Protection Plan (SPP) is not insurance. This is a licensed discount dental plan. SPP provides discounts only at Great Expressions Dental Centers for dental services. SPP does not make payments directly to the providers of dental services. You (member) will be required to pay for all health care or dental services but will receive a discount from Great Expressions Dental Centers, who have contracted with The CDl Group, Inc. Members will have 30 days after the effective date of enrollment to cancel their plan if they have not utilized and received discounts under the plan. Voucher must be present at time of office dental visit. The plan may not be used in conjunction with patient insurance. Valid only for option purchased. One take-home whitening kit per Smile Protection Plan voucher purchase, if applicable. This voucher is only redeemable at participating Texas-Area Great Expressions Dental Centers locations. Licensed and operated under Dr. April Kaneira. Value of savings for exams and X-rays with the Smile Protection Plan for 18 months are based on one examination every 6 months per individual. Value of savings is used for illustration purposes only. Actual savings may vary depending upon frequency of use. Six-month extension begins immediately after the end of the 12-month plan.',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/443331/click?api_key=FvDeXygs',
            'price': 99.0,
            'value': 282.0,
            'discount_amount': 183.0,
            'discount_percentage': 0.648936170212766,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Dental',
            'category_slug': 'dental',
            'image_url': 'https://api.discountapi.com/v2/deals/443331/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-08-01T04:59:59Z',
            'created_at': '2018-03-30T10:47:32Z',
            'updated_at': '2018-03-30T10:47:32Z',
            'merchant': {
                'id': 205663,
                'name': 'Great Expressions Dental Centers',
                'address': '1200 Paluxy Medical Circle',
                'locality': 'Granbury',
                'region': 'TX',
                'postal_code': '76048',
                'country': 'US',
                'latitude': 32.4249075,
                'longitude': -97.80825399999999,
                'phone_number': '+18175738338'
            }
        }
    }],
    'dermatology': [],
    'dining-nightlife': [],
    'electronics': [],
    'eye-vision': [],
    'facial': [],
    'fashion_accessories': [],
    'fitness': [],
    'fitness_product': [],
    'fitness-classes': [{
        'deal': {
            'id': 150306,
            'title': '10 or 20 Yoga Classes, or One Month of Unlimited Yoga for One or Two People at Miami Life Center (Up to 78% Off)',
            'short_title': 'Up to 78% Off Yoga Classes at Miami Life Center',
            'description': 'Choice of: 10 Yoga Classes 20 Yoga Classes One Month of Unlimited Yoga One Month of Unlimited Yoga for Two People See the schedule',
            'fine_print': 'Registration required. Must activate by expiration date on voucher; membership expires 90 days from activation date. Limit 1 per person, may buy 2 additional as gifts. Limit 1 per visit. May redeem across visits. Valid only for option purchased. All goods or services must be used by the same person. Valid only for guided classes (intro yoga, half primary, full primary, and yin yoga). Not valid for clients active in the last 12 month(s). Valid only for Miami residents. Proof of residency required at registration.',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/150306/click?api_key=FvDeXygs',
            'price': 89.0,
            'value': 400.0,
            'discount_amount': 311.0,
            'discount_percentage': 0.7775,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Fitness Classes',
            'category_slug': 'fitness-classes',
            'image_url': 'https://api.discountapi.com/v2/deals/150306/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-06-16T00:00:00Z',
            'created_at': '2018-02-16T15:56:00Z',
            'updated_at': '2018-04-15T12:51:54Z',
            'merchant': {
                'id': 98062,
                'name': 'Miami Life Center',
                'address': '736 6th Street',
                'locality': 'Miami Beach',
                'region': 'FL',
                'postal_code': '33139',
                'country': 'US',
                'latitude': 25.7757211,
                'longitude': -80.13586710000001,
                'phone_number': '+13055348988',
                'url': 'http://www.miamilifecenter.com'
            }
        }
    }, {
        'deal': {
            'id': 69232,
            'title': '14-Day or 7-Day Personal Training Programs for One or Two People at My House Fitness (Up to 72% Off)',
            'short_title': 'Up to 72% Off Personal-Training Programs at My House Fitness',
            'description': 'Choice of: 7-Day Small-Group Personal-Training Program for One Person 7-Day Small-Group Personal-Training Program for Two People 14-Day Small-Group Personal-Training Sessions with Meal Plan for One Person 14-Day Small-Group Personal-Training Sessions with Meal Plan for Two People',
            'fine_print': 'May be repurchased every 120 days. Registration required. Limit 1 per person, may buy 1 additional as gift. Limit 1 per visit. Valid only for option purchased. Consultation required. Non-candidates and other refund requests will be honored prior to any service being provided.',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/69232/click?api_key=FvDeXygs',
            'price': 55.0,
            'value': 185.0,
            'discount_amount': 130.0,
            'discount_percentage': 0.7027027027027027,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Fitness Classes',
            'category_slug': 'fitness-classes',
            'image_url': 'https://api.discountapi.com/v2/deals/69232/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-06-16T00:00:00Z',
            'created_at': '2018-02-16T15:00:18Z',
            'updated_at': '2018-04-15T13:18:29Z',
            'merchant': {
                'id': 48824,
                'name': 'My House Fitness',
                'address': '1295 Tuskawilla Rd #1001',
                'locality': 'Winter Springs',
                'region': 'FL',
                'postal_code': '32708',
                'country': 'US',
                'latitude': 28.6511019,
                'longitude': -81.2698391,
                'phone_number': '+18885244047',
                'url': 'http://myhousefitness.com/'
            }
        }
    }],
    'food_alcohol': [],
    'food-grocery': [],
    'gay': [],
    'gifts': [],
    'golf': [],
    'gym': [],
    'hair-removal': [{
        'deal': {
            'id': 288219,
            'title': 'One or Three Brazilian Waxing Sessions at Wax, Thread & Scissors (Up to 47% Off)',
            'short_title': 'Up to 47% Off Waxing at Wax, Thread & Scissors',
            'description': 'Choice of: One Brazilian Waxing Session Three Brazilian Waxing Session',
            'fine_print': "May be repurchased every 120 days, Promotional value expires 120 days after purchase. Amount paid never expires. Not valid for clients active in the past 12 months. Appointment required, subject to availability. Limit 1 per person. Valid only for option purchased. All goods or services must be used by the same person. Cannot be combined with any other offer or promotion. Merchant's standard cancellation policy applies. (any fees not to exceed voucher price). Merchant is solely responsible to purchasers for the care and quality of the advertised goods and services.",
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/288219/click?api_key=FvDeXygs',
            'price': 58.5,
            'value': 105.0,
            'discount_amount': 46.5,
            'discount_percentage': 0.44285714285714284,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Hair Removal',
            'category_slug': 'hair-removal',
            'image_url': 'https://api.discountapi.com/v2/deals/288219/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-06-23T00:00:00Z',
            'created_at': '2018-02-23T18:26:57Z',
            'updated_at': '2018-04-15T11:02:04Z',
            'merchant': {
                'id': 125297,
                'name': 'Wax, Thread & Scissors',
                'address': '2221 Peachtree Road Northeast',
                'locality': 'Atlanta',
                'region': 'GA',
                'postal_code': '30309',
                'country': 'US',
                'latitude': 33.8145732,
                'longitude': -84.3911517,
                'url': 'http://waxthreadandscissors.com/'
            }
        }
    }],
    'hair-salon': [],
    'health-beauty': [{
        'deal': {
            'id': 68027,
            'title': '1, 6, or 12 LED MyLipo Sessions at Color of Beauty Tanning Salon (Up to 70% Off)',
            'short_title': 'Up to 70% Off at Color of Beauty Tanning Salon',
            'description': 'Choice of: 1 LED MyLipo Session 6 LED MyLipo Sessions 12 LED MyLipo Sessions Laser Body Contouring: Shrinking Cells Check out Groupon’s guide to blade-free laser body contouring. A noninvasive alternative to traditional liposuction, laser body contouring relies on light rather than scalpels. During the procedure, a technician applies special pads to the body or moves a hand-piece over the skin. The device directs laser energy into the fat cells, causing them to rupture and release their liquid contents through a temporary pore in the cell membrane. The body then naturally disposes of the released matter—most likely through the lymphatic system, though scientists aren’t certain about the precise path the fat takes through the body’s system of trash compactors and back alleys. As the fat is burned by the body’s metabolism over the next few weeks, the treated area may appear more contoured, though results aren’t comparable to surgery and progress is measured in inches rather than pounds. (Since the cells are emptied, not removed, they’re not immune to later weight gain, either.) All this takes place well below the surface of the skin, and no downtime is required typically. The first low-level body-sculpting laser was actually used as a supplement to, rather than a replacement for, traditional liposuction. Low-level laser therapy had been used for some years as a treatment for pain and inflammation when a team of Colombian plastic surgeons led by Dr. Rodrigo Neira decided to use it to make incision-based liposuction more comfortable. When they applied the laser before treatment, they discovered that it made the fat far softer and easier to drain, prompting Neira to develop a system for standalone body-sculpting use.',
            'fine_print': "Must sign waiver. Appointment required. Merchant's standard cancellation policy applies (any fees not to exceed voucher price). Limit 1 per person, may buy 1 additional as gift. Valid only for option purchased. All goods or services must be used by the same person. May be repurchased every 30 days.",
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/68027/click?api_key=FvDeXygs',
            'price': 70.5,
            'value': 200.0,
            'discount_amount': 129.5,
            'discount_percentage': 0.6475,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Health & Beauty',
            'category_slug': 'health-beauty',
            'image_url': 'https://api.discountapi.com/v2/deals/68027/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-06-16T00:00:00Z',
            'created_at': '2018-02-16T14:59:24Z',
            'updated_at': '2018-04-15T11:54:06Z',
            'merchant': {
                'id': 48180,
                'name': 'Color of Beauty Tanning Salon',
                'address': '36 E 17th Ave',
                'locality': 'Eugene',
                'region': 'OR',
                'postal_code': '97401',
                'country': 'US',
                'latitude': 44.040978,
                'longitude': -123.092241,
                'phone_number': '+15416868846',
                'url': 'http://www.colorofbeautytan.com/'
            }
        }
    }],
    'home_goods': [],
    'home-services': [{
        'deal': {
            'id': 14490,
            'title': 'Two or Four Hours of Basic Cleaning from Divas Cleaning Services (Up to 43% Off)',
            'short_title': 'Up to 43% Off Services from Divas Cleaning Services',
            'description': 'Choice of: Two Hours of Basic Residential or Commercial Cleaning Four Hours of Basic Residential or Commercial Cleaning Dust Mites: Invisible Flesh Eaters Dust mites exist wherever humans do, eating our shed skin and making our eyes itchy. Read on for more about these tiny garbage disposals. Dust mites are permanent houseguests, freeloading off of our dead skin cells and making themselves comfortable in our beds. Unlike a distant relative or a persistent vacuum salesman, they’re hard to kick out since they’re nearly impossible to see. Each mite measures about 1/80th of an inch, visible only under the lens of a microscope. Close up, they echo back to something prehistoric. Their eight legs are equipped with suckers and hooks, and their thick bodies seem to be covered in armored plates. In fact, fossil evidence suggests that mites have been on Earth for 400 million years, predating dinosaurs by more than 100 million years. And since that time, they’ve made themselves at home inside damp, dark spaces brimming with dead skin cells, their current favorite homes being carpets, duvets, and pillowcases. Humans make it easy for mites to find food, since we shed about 1.5 million skin flakes every hour. Although our relationship with mites is partially symbiotic—they do dispose of our biological waste—mites also pose a health threat, especially to children. Their droppings can trigger asthmatic reactions in those with mite allergies, and their terrifying appearance can give any kid with a microscope a new reason to fear the boogeyman under the bed.',
            'fine_print': 'May be repurchased every 180 days. Valid only within 20 miles of zip code 19129. Limit 1 per person, may buy 1 additional as gift. Limit 1 per visit. Limit 1 per household. Must use promotional value in 1 visit. Valid only for option purchased. Not valid towards a deep clean.',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/14490/click?api_key=FvDeXygs',
            'price': 99.0,
            'value': 175.0,
            'discount_amount': 76.0,
            'discount_percentage': 0.4342857142857143,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Home Services',
            'category_slug': 'home-services',
            'image_url': 'https://api.discountapi.com/v2/deals/14490/image?api_key=FvDeXygs',
            'online': True,
            'expires_at': '2018-06-16T00:00:00Z',
            'created_at': '2018-02-16T13:46:47Z',
            'updated_at': '2018-04-09T13:22:14Z',
            'merchant': {
                'id': 10909,
                'name': 'Divas Cleaning Services',
                'url': 'http://divascleaning.com/'
            }
        }
    }],
    'jewish': [],
    'kids': [],
    'kitchen': [],
    'kosher': [],
    'life-skills-classes': [],
    'luggage': [],
    'makeup': [],
    'manicure-pedicure': [],
    'martial-arts': [],
    'massage': [],
    'mens-clothing': [],
    'mens_fashion': [],
    'mobile': [],
    'movies_music_games': [],
    'museums': [],
    'office_supplies': [],
    'outdoor-adventures': [{
        'deal': {
            'id': 90784,
            'title': 'Swim with Dolphins in Mexico, Caribbean and Jamaica at Dolphin Discovery (Up to 38% Off). 15 Locations Available',
            'short_title': 'Up to 38% Off at Dolphin Discovery',
            'description': 'Choose from 29 Options Cancun-Isla Mujeres: Dolphin Encounter Dolphin Royal Swim VIP Cozumel: Dolphin Encounter Dolphin Royal Swim Playa del Carmen: Dolphin Encounter Dolphin Royal Swim Tulum/Akumal: Dolphin Encounter Dolphin Royal Swim Puerto Aventuras/Riviera Maya: Dolphin Encounter Dolphin Royal Swim Los Cabos: Dolphin Encounter Dolphin Royal Swim Plus Puerto Vallarta: Dolphin Encounter Dolphin Royal Swim Saint Kitts: Dolphin Encounter Dolphin Royal Swim Anguila: Dolphin Encounter Dolphin Royal Swim Dolphin Cayman: Dolphin Lovers Swim Dolphin Royal Swim Cove Cayman: Dolphin Lovers Swim Dolphin Royal Swim Punta Cana: Dolphin Encounter Dolphin Royal Swim Tortola: Dolphin Discovery Swim Dolphin Cove Montego Bay: Dolphin Encounter Dolphin Royal Swim Dolphin Cove Ocho Rios: Dolphin Encounter Dolphin Royal Swim Click here and select location to view FAQ’s. Visit on Facebook',
            'fine_print': "Reservation required at least 4 days in advance. Subject to availability. Merchant's standard cancellation policy applies (any fees not to exceed voucher price). Limit 20 per person. Valid only for option purchased. Visit site and click on location for FAQ's. Valid passport required as services are at locations outside the United States. For the Cancun-Isla Mujeres options only, $8 docking fee per person not included.",
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/90784/click?api_key=FvDeXygs',
            'price': 125.0,
            'value': 179.0,
            'discount_amount': 54.0,
            'discount_percentage': 0.3016759776536313,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Outdoor Adventures',
            'category_slug': 'outdoor-adventures',
            'image_url': 'https://api.discountapi.com/v2/deals/90784/image?api_key=FvDeXygs',
            'online': True,
            'expires_at': '2018-06-16T00:00:00Z',
            'created_at': '2018-02-16T15:14:50Z',
            'updated_at': '2018-04-15T12:03:37Z',
            'merchant': {
                'id': 60092,
                'name': 'Dolphin Discovery',
                'url': 'https://www.dolphindiscovery.com/grouponusa/'
            }
        }
    }],
    'personal-training': [],
    'pets': [],
    'photography-services': [{
        'deal': {
            'id': 241831,
            'title': 'Photo Shoot Package with Optional Digital Image at JCPenney Portraits (Up to 89%)',
            'short_title': 'Up to 89% Off Photo Shoot Package at JCPenney Portraits',
            'description': 'Choose Between Two Options $10.99 for an in-studio photo shoot with 4 standard prints of one pose ($99.92 value) Valid for one 8x10, two 5x7, eight wallets and one enhanced print Free professional photo shoot, no sitting fees 40% off additional prints, wall art, canvas prints, photo collections and full high-resolution digital album Pet photos now available. Click here for details $19.99 for an in-studio photo shoot with one high-resolution digital image and 4 standard prints of one pose ($149.91value) Valid for one high-res digital image, one 8x10, two 5x7, eight wallets and one enhanced print Discount to upgrade to the full high-resolution digital album Free professional photo shoot, no sitting fees 40% off additional prints, wall art, canvas prints, photo collections Pet photos now available. Click here for details Click here to find the location nearest you. Like JCPenney Portraits on Facebook.',
            'fine_print': 'May buy multiple. Limit 1 per family, per day. Valid only for option purchased. Valid at any JCPenney Portraits location. Appointment required. Cannot be combined with any other offers. Additional 40% discount not valid toward reorders, studio events, other media, services, featured products, or online orders. Not valid toward previous photo shoot. Photo shoot and order must be completed by expiration date. After expiration, price paid for voucher may be applied toward future standard portrait purchases. Not valid for outdoor photography. May be repurchased every 30 days.',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/241831/click?api_key=FvDeXygs',
            'price': 19.99,
            'value': 149.91,
            'discount_amount': 129.92,
            'discount_percentage': 0.8666533253285303,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Photography Services',
            'category_slug': 'photography-services',
            'image_url': 'https://api.discountapi.com/v2/deals/241831/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-06-16T00:00:00Z',
            'created_at': '2018-02-16T17:13:18Z',
            'updated_at': '2018-04-15T11:29:15Z',
            'merchant': {
                'id': 146861,
                'name': 'JCPenney Portrait Studio',
                'address': '1100 Ogden Ave.',
                'locality': 'Montgomery',
                'region': 'IL',
                'postal_code': '60538',
                'country': 'US',
                'latitude': 41.7185063,
                'longitude': -88.2876482,
                'phone_number': '+16303759761',
                'url': 'http://www.jcpportraits.com/'
            }
        }
    }],
    'pilates': [],
    'product': [],
    'restaurants': [{
        'deal': {
            'id': 107374,
            'title': 'Reserve Wine Tasting for Two, Four, or Up to 10 with Optional Tour at Sanctuary Vineyards (Up to 51% Off)',
            'short_title': 'Up to 51% Off at Sanctuary Vineyards',
            'description': 'Choice of: Reserve Wine Tasting for Two with Optional Tour (Valid Monday - Thursday) Reserve Wine Tasting for Two with Optional Tour (Valid Friday - Sunday) Reserve Wine Tasting for Four with Optional Tour (Valid Monday - Thursday) Reserve Wine Tasting for Four with Optional Tour (Valid Friday - Sunday) Private Reserve Wine Tasting for Up to 10 with Optional Tour Reservation Required',
            'fine_print': 'Reservation required. Limit 1 per person, may buy 1 additional as gift. Limit 1 per visit. Valid only for option purchased. Optional tour only available on Wednesday. Private wine tasting must be scheduled in advance. Tours and private tasting subject to availability. Alcohol is not discounted. Must be 21+ with valid ID.',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/107374/click?api_key=FvDeXygs',
            'price': 125.0,
            'value': 250.0,
            'discount_amount': 125.0,
            'discount_percentage': 0.5,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Restaurants',
            'category_slug': 'restaurants',
            'image_url': 'https://api.discountapi.com/v2/deals/107374/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-06-16T00:00:00Z',
            'created_at': '2018-02-16T15:29:10Z',
            'updated_at': '2018-04-15T12:12:12Z',
            'merchant': {
                'id': 68495,
                'name': 'Sanctuary Vineyards',
                'address': '7005 Caratoke Highway',
                'locality': 'Jarvisburg',
                'region': 'NC',
                'postal_code': '27947',
                'country': 'US',
                'latitude': 36.2062881,
                'longitude': -75.8645408,
                'phone_number': '+12524912387',
                'url': 'http://sanctuaryvineyards.com/'
            }
        }
    }, {
        'deal': {
            'id': 291801,
            'title': 'Pizza Meal for Two or Four or Chicken-Parmigiana Meal for Eight at Harrison Pizza and Pasta (Up to 58% Off)',
            'short_title': 'Up to 58% Off at Harrison Pizza and Pasta',
            'description': 'Choose from Three Options $14 for pizza meal for two or more ($28.97 value) One extra-large, cheese pizza ($14.99 value) Salad with choice of dressing ($5.99 value) One ziti with tomato sauce ($7.99 value) $23 for pizza meal for four or more ($49.95 value) Two extra-large, cheese pizzas ($29.98 value) Two salads with choice of dressing ($11.98 value) One ziti with tomato sauce ($7.99 value) $33 for a chicken parmesan dinner for eight or more ($78 value) One tray of chicken parmesan ($49 value) One of salad with choice of dressing ($29 value) See the full menu. This Groupon is not valid on Fridays.',
            'fine_print': 'Limit 1 per person. Limit 1 per visit. Limit 1 per table. Valid only for option purchased. Not valid Fridays. Must call two hours ahead to place order.',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/291801/click?api_key=FvDeXygs',
            'price': 14.0,
            'value': 28.97,
            'discount_amount': 14.969999999999999,
            'discount_percentage': 0.5167414566793235,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Restaurants',
            'category_slug': 'restaurants',
            'image_url': 'https://api.discountapi.com/v2/deals/291801/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-06-23T00:00:00Z',
            'created_at': '2018-02-23T18:33:13Z',
            'updated_at': '2018-04-15T14:28:12Z',
            'merchant': {
                'id': 132725,
                'name': 'Harrison Pizza and Pasta',
                'address': '248 Halstead Ave',
                'locality': 'Harrison',
                'region': 'NY',
                'postal_code': '10528',
                'country': 'US',
                'latitude': 40.968218,
                'longitude': -73.714076,
                'phone_number': '+19148350135',
                'url': 'http://harrisonpizza.com/'
            }
        }
    }],
    'retail-services': [],
    'skiing': [],
    'skydiving': [],
    'spa': [],
    'special-interest': [],
    'sporting-events': [],
    'tanning': [],
    'teeth-whitening': [{
        'deal': {
            'id': 371713,
            'title': '$99 for Zoom! Teeth Whitening, Exam, and X-rays at Dossett Dental ($1,075 Value). Five Locations Available.',
            'short_title': '91% Off Whitening and Exam at Dossett Dental',
            'description': 'Transporting loads of foodstuffs and sugar snacks over pearly cobblestone mouth roads can result in potholes and bridge problems. Maintain your digestive highway with this voucher. $99 for a Teeth-Whitening Package ($1,075 Total Value) Two 15-minute Zoom! whitening sessions (an $850 value) 45-minute exam, including x-rays (a $225 value) A cleaning is an additional $98 (without insurance).',
            'fine_print': 'Limit 1 per person, may buy 1 additional as a gift. Limit 1 per visit. Valid only for location purchased. Appointment required. Not valid for patients with periodontal or gum disease. May be repurchased every 30 days.',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/371713/click?api_key=FvDeXygs',
            'price': 99.0,
            'value': 1075.0,
            'discount_amount': 976.0,
            'discount_percentage': 0.9079069767441861,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Teeth Whitening',
            'category_slug': 'teeth-whitening',
            'image_url': 'https://api.discountapi.com/v2/deals/371713/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-09-12T00:00:00Z',
            'created_at': '2018-03-16T09:08:07Z',
            'updated_at': '2018-04-15T12:03:04Z',
            'merchant': {
                'id': 181416,
                'name': 'Dossett Dental',
                'address': '6009 W Parker Rd. at The Tollway',
                'locality': 'Plano',
                'region': 'TX',
                'postal_code': '75093',
                'country': 'US',
                'latitude': 33.0456375,
                'longitude': -96.8316818,
                'phone_number': '+19722658285'
            }
        }
    }],
    'theater': [],
    'tools': [],
    'toys': [],
    'travel': [],
    'treats': [],
    'unknown': [{
        'deal': {
            'id': 464178,
            'title': 'One-Week Summer Camp at Spirals Gym & Ed-Venture Kids Center (Up to 54% Off). Three Options Available.',
            'short_title': 'Up to 54% Off Camp at Spirals Gym & Ed-Venture Kids Center',
            'description': 'Choice of: Mansfield Location: One-Week Half-Day Ed-Venture Summer Camp for Ages 3–5 Mansfield Location: One-Week Full-Day Ed-Venture Summer Camp for 1st–6th Grade Kennedale Location: One-Week Full-Day Ed-Venture Summer Camp for 1st–6th Grade Full-Day Camp; Dates and camps’ themes on which each week’s activities are based: Week 1: May 29-June 1 - Spirals Super Heroes Week 2: June 4-8 - Wild Wild West Week 3: June 11-15 - Pokemon Go Crazy Week 4: June 18-22 - Harry Potter Week Week 5: June 25-29 - Outer Space Week Week 6: July 2-6 - Rockin’ in the USA Week 7: July 9-13 - Oceanic Awesome! Week 8: July 16-20 - Olympic Gold Week 9: July 23-27 - Minute to Win It Week 10: July 30 - Aug 3 - Slimed! Week 11: Aug 6-10 - Under the Big Top Half-Day Camp; Dates and camps’ themes on which each week’s activities are based: Week 1: May 29 - June 1 - Architect Week (Lego) Week 2: June 4-8 - Kids in the Kitchen Week 3: June 11-15 - Incredible Athletes Week 4: June 18-22 - Exploration Week 5: June 25-29 - Outer Space Week Week 6: July 2-6 - NO CAMP OFFERED Week 7: July 9-13 - Let’s Pretend Week 8: July 16-20 - Ball Camp Week 9: July 23-27 - Animal Planet Week 10: July 30 - Aug 3 - Little Artists Week 11: Aug 6-10 - NO CAMP OFFERED Ed-Venture Summer Camp Ed-Venture Camp aims to provide a quality program that encourages kids to challenge themselves and develop good sportsmanship and team-work skills while enjoying a fun and active experience. Using games and team-building activities, the staff encourages campers to set personal goals and work toward achieving them. They also map out nine different goal setting categories and conclude each week with an award ceremony to acknowledge the campers achievements for that week.',
            'fine_print': 'New families only. Reservation required 72 hours in advance. Subject to availability. Limit 1 per person, may buy 1 additional as gift. Limit 1 per visit. Valid only for option purchased. Limit 1 per family. Must complete registration form and sign online waiver. $20 camp registration fee not included. Valid for ages 3-13. All goods or services must be used by the same person. Limited space available. Closed on July 4.',
            'number_sold': 0,
            'url': 'https://api.discountapi.com/v2/deals/464178/click?api_key=FvDeXygs',
            'price': 45.0,
            'value': 98.0,
            'discount_amount': 53.0,
            'discount_percentage': 0.5408163265306123,
            'provider_name': 'Groupon',
            'provider_slug': 'groupon',
            'category_name': 'Unkown',
            'category_slug': 'unknown',
            'image_url': 'https://api.discountapi.com/v2/deals/464178/image?api_key=FvDeXygs',
            'online': False,
            'expires_at': '2018-07-27T04:59:59Z',
            'created_at': '2018-04-06T11:32:48Z',
            'updated_at': '2018-04-15T12:03:37Z',
            'merchant': {
                'id': 210305,
                'name': 'Spirals Gym & Ed-Venture Kids Center',
                'address': '1083 Bowman Springs Rd.',
                'locality': 'Kennedale',
                'region': 'TX',
                'postal_code': '76060',
                'country': 'US',
                'latitude': 32.659494,
                'longitude': -97.2259436,
                'phone_number': '+18175162100'
            }
        }
    }],
    'wine-tasting': [],
    'womens-clothing': [],
    'women_fashion': [],
    'yoga': []
}


rmn_deals = {
  'Bed Bath and Beyond': ['20% Off 1 Item Sitewide Instantly'],
  "Macy's": ['Extra 20% Off Memorial Day Sale', 'Up to $25 Cash Back for Online Purchases Sitewide', 'Free Deluxe Size Perfume of Your Choice With $35 Order for Beauty Insider Members', '10% Visitor Savings Pass', 'Extra 20% Off Memorial Day Sale', 'Up to an Extra 20% Off Select Sale Items'],
  'Ulta': ['20% Off Any One Qualifying Item', '$3.50 Off Orders of $15 + Free Shipping on $50+ & Free Samples', '$5 Cash Back for Online Purchases of $40 Sitewide', 'Freebies From ULTA'],
  'Bath & Body Works': ['20% Off Sitewide', '$10 Off $30+ Storewide', 'Free Hand Soap'],
  'Sephora': ['Free Gift With $25 Purchase for Beauty Insiders', 'Up to $20 Cash Back for Online Purchases Sitewide', '3 Free Samples In-store And Online', '$5 Cash Back for Online Purchases of $75+ Sitewide'],
  'Great Clips': ['Great Clips Coupons, In-Store Offers And Promo Codes'],
  'FragranceNet.com': ['37% Off Sitewide', '33% Off Sitewide', '50% Off Perfume Specials'],
  'Tarte': ['20% Off Your Purchase + Free Deluxe Gift', '15% Off Your Order + Free Sample + Free Shipping on $40'],
  'Glossier': ['10% Off Your First Purchase'],
  'e.l.f. Cosmetics': ['$5 Off $20 + Free Shipping + Free 3-Piece Gift With $25 Purchase', '15% Off Sitewide for MAC Select Members', '$5 Off $20 Or More + Free 2-Piece Gift & Free Shipping Over $25'],
  'JCPenney': ['20% Off Your Order', 'Free Shipping Everyday Anywhere Over $99, Or To Stores Over $49', 'Extra 20% OffIn-Store & Online', '$10 Off $25+In-Store And Online'],
  'Perfumania': ['$10 Off $100+ In-store & Online + Free Shipping on $55+'],
  'Birchbox': ['15% Off $35+ Orders'],
  'Madison Reed': ['Free Radiant Cream Color Kit on First Order', 'Free Shipping on Your First Box of Permanent Hair Color'],
  'Dove': ['$2 Off Dove Soap Bar'],
  'Amazon': ['Outlet Deals - Up to 50% Off Kitchen, Outdoor & Beauty!'],
  'Avon': ['$10 Cash Back for Online Purchases of $50+ Sitewide'],
  'Too Faced Cosmetics': ['20% Off Your Order'],
  'Nordstrom': ['Free Gift With $55 Purchase'],
  'The Body Shop': ['15% Off Your Next Purchase When You Sign Up for Emails'],
  'Sams Beauty': ['Shipping for $4'],
  'BH Cosmetics': ['Extra 5% Off Sitewide + Free Shipping on $50+'],
  "Paula's Choice Skincare": ['20% Off One Item'],
  "Kohl's": ['$10 Off $25+', '15% Off $100+'],
  'Target': ['$5 Off $50 Select Items + Free Standard Shipping on Qualifying Purchases', '$5 Off $50 Apparel, Shoes & Accessories', '40% Off Sandals, Flip-flops & Canvas Shoes'],
  'Fashion Nova': ['30% Off Your Order + Free Shipping'],
  "Carter's": ['Extra 20% Off Your Purchase of $40 Or More', 'Extra 15% Off Sitewide'],
  'Old Navy': ['20% Off Your Purchase'],
  'Venus': ['Extra 10% Off Sitewide + $4.95 Shipping on Purchases Under $100 Or Free Ground Shipping on Purchases of $100+'],
  'Forever 21': ['Extra 30% Off Sale', '10% Off Your Next Order When You Sign Up for Email'],
  'American Eagle Outfitters': ['25% Off Your Purchase When You Sign-up for Tailgate Emails for AE', 'Up to 60% Off AEO Tops, Bottoms, Footwear & More at AE'],
  'New York & Company': ['Exclusive! 50% Off Sitewide + Extra 10% Off Your Entire Order'],
  'FarFetch.com': ['Extra 10% Off Sitewide'],
  "The Children's Place": ['$10 Off Next Purchase of $40+ With Text Alerts Sign Up'],
  'J. Crew Factory': ['15% Off Sitewide for College Students And Teachers'],
  'Express': ['20% Off Your First Purchase When You Sign-up for Email'],
  "Victoria's Secret": ['Free Standard Shipping for Orders $50 Or More'],
  'Shopbop': ['Extra 15% Off Your Purchase'],
  'Hollister': ['40% Off Sitewide + Free Shipping on All Orders'],
  'Dolls Kill': ['15% Off Sitewide'],
  'thredUP': ['$10 Off Your Purchase'],
  'Soma': ['Extra 20% Off Sitewide'],
  'Bare Necessities': ['20% Off Your Purchase'],
  'Stein Mart': ['Extra 20% Off Any One Sale Item'],
  'Threadless': ['Free Shipping on Order of $45+'],
  'Belk': ['Extra $10 Off Purchases of $40+', 'Extra 25% Off Regular & Sale Purchases + 20% Off Home & Shoes'],
  'Lane Bryant': ['Extra $10 Off $25+ on Select Items'],
  'Anthropologie': ['Free Shipping Sitewide Orders Over $150 for AnthroPerks Members'],
  'Under Armour': ['40% Off UA Factory House + Extra 10% Off', '$20 Cash Back for Online Purchases of $100+ Sitewide'],
  'She In': ['20% Off Your Order'],
  'Chadwicks': ['20% Off Sitewide'],
  'J. Crew': ['40% Off Full Price Purchase'],
  'Urban Outfitters': ['20% Off Sitewide When You Sign Up for Rewards Member'],
  'Charlotte Russe': ['Up to $25 Off With Minimum Spend'],
  'Buffalo Wild Wings': ['Buffalo Wild Wings Coupons & Deals', 'Buffalo Wild Wings Coupons & Deals'],
  "Papa John's": ['2 Large 1 Topping Pizzas for $7.77 Each', '20% Off Your Order', 'One Large One Topping Pizza 1-2 Liter Pepsi And 1- Bread Side All for $12.99 Special', '25% Off Regular Menu Price Order', '25% Off Regular Menu Price', 'Two Large 1-Topping Pizzas for $7.77 Each', '40% Off Regular Menu Price Orders & 10% of The Discounted Purchase Will Be Donated To Autism Speaks', 'Free Large One Topping Pizza', 'Free Large 2 Topping Pizza on 20 Points for Papa Rewards Members', 'Large Or Pan 1-Topping Pizza for $7', 'Any Large Five Topping Or Specialty Pizza Just $13.99', 'Large 2 Topping Pizza for $7.99', '2 Large 1 Topping Pizzas for $7.77 Each'],
  "D'Angelo Sandwich": ['30% Off Your Order', '30% Off Your Order'],
  'Noodles and Company': ['$4 Off First Purchase + Free Cookie', '$4 Off Your Order of $10', '$4 Off First Purchase + Free Cookie'],
  "Hungry Howie's": ['Free Howie Bread With Any Online Order of $12+', '50% Off Your Next Order', 'Medium 1-Topping Pizza for $5 When You Buy 2', 'Free Howie Bread With Any Online Order of $12+'],
  'Wingstop': ['Free Large Fresh-Cut Seasoned Fries When Sign-Up With E-Club', 'Free Large Fresh-Cut Seasoned Fries When Sign-Up With E-Club'],
  'Round Table Pizza': ['15% Off Your Order', 'Any Large Specialty Pizza for $19.99', '6 Free Garlic Parmesan Twists With Purchase of Any Large Premium Speciality Pizza at Regular Price', '15% Off Your Order'],
  'Pizza Hut': ['Large 2-Topping Pizza for $7.99', '2 Medium Pizzas With 2 Toppings Each for $5.99', '25% Off Your Order', '40% Off Pizza', '$11 Any Deal', 'Buy 1 Large Pizza, Get 1 Large Pizza Free', 'Large Specialty Or Up to 5 Topping Pizza for $7.99', 'Big Pizza Deal for $19.99!', '30% Off Your Order', '$5 Off Orders of $15 Or More', 'Up to 50% Off With Pizza Hut Coupons, Promo Codes, & Deals', '$10 Any Large Carryout Pizza', '50% Off Menu-priced Pizzas at Participating Locations', '30% Off Online Orders at Participating Stores', 'Large 2-Topping Pizza for $7.99'],
  "Applebee's": ['Lunch Combos for $6.99', '$5 Off First Online Or App Carside To Go Order of $25+', '$12.99 Grill Combos', 'Lunch Combos for $6.99'],
  'Panera Bread': ['50% Off Shipping', '50% Off Online Delivery Order', 'Free Pastry Or Sweet Coupon When You Sign Up for My Panera Email', '50% Off Panera Delivery at Chicagoland'],
  'Golden Corral': ['Senior Discount'],
  'Ruby Tuesday': ['$5 Off $15 Food Purchase'],
  'Popeyes': ['$4 Wicked Chicken Special', '10 Pieces of Mixed Or Tender Chicken + 2 Large Sides + 5 Biscuits for $20'],
  'Eat24': ['$10 Off Your First Order of $15 When Your Order When You Sign Up for Email', '$5 Off Your Order'],
  'Papa Murphy': ["Instant Coupon Through Papa Murphy's Text Club", "Sign Up for Papa Murphy's EClub for Exclusive Coupons"],
  'Chipotle': ['Free Guac Or Queso W/ App Download'],
  'Bob Evans': ['20% Off Your Purchase'],
  'Subway': ['Select Footlong Sandwiches for $4.99', 'Five Footlongs for $4.99 Each', '$2.99 6" Sub With Sign Up for Text Offers'],
  'Donatos': ['$3 Off Any Large Pizza', '$3 Off $15+', '$5 Off Any Two Large Pizzas'],
  'Olive Garden': ['Early Dinner Duos for $8.99', 'Free Appetizer Or Desert With Email Signup', 'Latest Olive Garden Specials'],
  "Domino's": ['Free 2-Piece Order of Chocolate Lava Crunch Cakes', 'Medium Specialty Pizza for $7.99 + Select Sides for $5.99 Each', '1 Medium 2-Topping Pan Pizza for $8.99', 'Large Pizza With Up to 5 Toppings Carryout Only for $9.99'],
  'GrubHub': ['$10 Off Orders of $15+'],
  'Outback Steakhouse': ['$5 Off 2 Adult Dinner Entrees With Outback App'],
  'Panda Express': ['4 Free Bottled Drinks on Any 2 Large Sides And 3 Large Entrees'],
  'Burger King': ['BOGO Free Whopper & More Coupons With BK App Download'],
  'Boston Market': ['$3 Off $10 Purchase Sitewide'],
  "Marco's Pizza": ['XLarge 1-topping Pizza for $9.99', 'Free CheezyBread at Your Local Store', 'Large Specialty Pizza for $12.99', '30% Off $20+'],
  'Souplantation': ['Lunch Combo for $11.99 With Beverage', '2 Dinner Combo for $25 With 2 Beverages'],
  'Cold Stone Creamery': ['Buy One Get One Free Coupon'],
  'Smashburger': ['Free Burger With Fry And Drink Purchase', 'Free Entree With App Download'],
  'Cicis': ['Free 1 Buffet Meal With Purchase of One Adult Buffet & 2 32oz Drinks Vlaid Certain Locations'],
  "Jet's Pizza": ['Join Jets E-Club for Special Coupons And Offers'],
  'KFC': ['$20 Family Fill Up'],
  'Wendys': ["Free Dave's Single Burger When You Enroll In Wendy's Rewards"],
  'IHOP': ['Join And Get Free Food With Pancake Revolution'],
  'Red Lobster': ['Red Lobster Coupons, Specials & Promos', '$3 Off Two Adult Lunch Entrees'],
  "Denny's": ["20% Off Your Next Visit When You Join for Denny's Rewards Program"],
  'Starbucks': ['Free Coupon for Coffee on Your Birthday With Rewards Program'],
  'Dickeys Barbecue Pit': ['50% Off Dickeys Barbecue'],
  'Sweet Tomatoes': ['2 Dinner Combo for $25 With 2 Beverages'],
  'Dunkin Donuts': ['Free Dunkinâ€™ Donuts Beverage When You Enroll In DD Perks on The App'],
  'Bellagios Pizza': ['$3 Off Your Orders'],
  'Corner Bakery Cafe': ['$10 Off $100+ Online Catering Order'],
  'El Pollo Loco': ['Specials And Promotions!'],
  'DSW': ['$10 Off Your Order When You Sign Up for Emails'],
  'Joes New Balance': ['25% Off Orders $125+ Plus Free Shipping'],
  'Nike': ['10% Off for Students', 'Up to 40% Off Select Sale'],
  'Shoes.com': ['30% Off Your Purchase + Free Shipping'],
  'Adidas': ['15% Off Your Purchase When You Sign Up for Newsletter', 'Shop on The Adidas Memorial Day Sale'],
  'Payless ShoeSource': ['Extra 30% Off In-Store', 'Extra $10 Off Your $25+ Purchase'],
  'PUMA': ['Extra 30% Off Sale Section + Free Shipping'],
  'Eastbay': ['10% Off Orders Over $50 + Free Shipping', '17% Off Orders of $120 + Free Shipping'],
  'New Balance': ['10% Off Your Purchase'],
  'Finish Line': ['Up to 50% Off End of Season Sale', '$5 Cash Back for Online Purchases of $25 Sitewide'],
  'Running Warehouse': ['10% Off Sitewide'],
  'Easy Spirit': ['30% Off Your Order'],
  'Journeys': ['$5 Off Your Order of $25 When You Sign Up for Email'],
  'Academy Sports + Outdoors': ['$10 Cash Back for Online Purchases of $75+ Sitewide'],
  'Vionic Shoes': ['Free Ground Shipping on Your Order'],
  'Sperry': ['20% Off Sperry Orders'],
  'Foot Locker': ['$20 Off $120 Order'],
  'Steve Madden': ['25% Off + Free Shipping'],
  'Dicks Sporting Goods': ["Dick's Sporting Goods Coupons, In-Store Offers, And Promo Codes"],
  'Shoes For Crews': ['15% Off Your Purchase'],
  'Reebok': ['Up to $20 Off With Minimum Spend'],
  'ALDO Shoes': ['15% Off Your First Purchase With Newsletter Sign-up'],
  'Vans': ['$5 Cash Back for Online Purchases of $35 Sitewide'],
  'ShoeStation': ["20% Off Men's, Women's & Children's Footwear"]
}